### ISSUE TITLE
Add GT Dataset for Malayalam

### ISSUE THREAD

**Issue by nidame** [HTR-United/htr-united#104]
Hi, we have exported the data from Transkribus in the ALTO format only because the Page XML export from Transkribus produces invalid data. Transkribus has confirmed that the TranskribusMetadata node is not valid with regards to the original XML schema. I suspect this will cause problems when importing the Page XML in eScriptorium.
How shall we handle this? Transkribus wants to solve this, but I have no information when.

**Comment by alix-tz** [comment]
This situation is linked to #60 

Can you build the description of the dataset with the ALTO files, but leave the PAGE files accessible in your repository?

**Comment by alix-tz** [comment]
Maybe simply make sure to keep the organization you have currently:
```
- data/
   - alto/
   - page/
   - images files, ...
```

**Comment by PonteIneptique** [comment]
This entry is being currently reviewed by @alix-tz for the PR. Sorry for the delay !
