### ISSUE TITLE
Add tags for silver datasets (and gold datasets)

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#114]
Opening this issue to start investigating ways to address the cases of silver datasets (datasets which may contain a few errors). It would make sense to be able to distinguish gold datasets from silver datasets, but this has a few implications on the interface, on the schema and on our capacity to control that a dataset is reliably tagged as Gold...

**Comment by alix-tz** [comment]
this issue is created after discussion raised in #102

**Comment by PonteIneptique** [comment]
Mostly been done in https://github.com/HTR-United/schema/pull/18
Done in the catalog as of https://github.com/HTR-United/htr-united.github.io/commit/ec3c38017f37bbb79d6bc8e024aeeb127113447a
