### ISSUE TITLE
3 datasets for Greek

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#136]
Consider contacting the authors of the following datasets to see if they would be interested in integrating their description in the catalog:

- https://zenodo.org/records/5595669#.YaneoLoxVPY
- https://zenodo.org/records/5578136#.YaneuboxVPY
- https://zenodo.org/records/5578251#.YaneyboxVPY

They're all cited in https://www.mdpi.com/2313-433X/7/12/260

**Comment by maxguen** [comment]
Consider also contacting the authors for this repo [https://github.com/vivianpl/HPGTR](https://github.com/vivianpl/HPGTR), also in ancient greek

Cited in [https://aclanthology.org/2022.lrec-1.708/](https://aclanthology.org/2022.lrec-1.708/)

**Comment by PonteIneptique** [comment]
Fixed by #156
