### ISSUE TITLE
Data without images

### ISSUE THREAD

**Issue by michaelscho** [HTR-United/htr-united#138]
Hi, I have quite a large set of annotated pageXML files containing layout information (~3000 pages). I want to make the data available via htr-united, but I am not sure if I can include images for copyright reasons. For my own repository, I create a json file with links to the images which can be used for downloading the images directly from the library. Will that be sufficient for htr-united as well or what is best practice in these cases?

**Comment by alix-tz** [comment]
Hello!
Thank you for reaching out! Yes, if you can't publish the images along with the dataset but provide a way for potential reusers to download the images files on their own, this is very acceptable! Simply, make sure to mention it in the description of the dataset. 

For us, all you need to do is fill the form (here: https://htr-united.github.io/document-your-data.html) and submit it to us for addition in the catalog.

Don't hesitate if you have other questions!

**Comment by michaelscho** [comment]
Thanks for you reply! It took me a bit to proceed in this matter but I now created json mappings such as
`   {
        "file_name": "B_0001.xml",
        "image_name": "B_0001.jpg",
        "image_url": "https://api.digitale-sammlungen.de/iiif/image/v2/bsb00140701_00001/full/1500,1840/0/default.jpg"
    },` 
I think that should do the trick. Thanks again!

**Comment by PonteIneptique** [comment]
Great ! :)
