### ISSUE TITLE
Vérification de ground truth pour DAHN

### ISSUE THREAD

**Issue by FloChiff** [HTR-United/htr-united#14]
Je voudrais vérifier que les ground truth et le README que j'ai ajouté dans le repository du projet DAHN sont conformes à ce qui est attendu avant de l'ajouter comme repository dans HTR-United:
[DAHN Corpus Ground truth](https://github.com/FloChiff/DAHNProject/tree/master/Project%20development/Training/Ground%20truth)

**Comment by alix-tz** [comment]
Je pense que pour le moment c'est bien. Je te ferai signe quand j'aurais le temps de me pencher sur la normalisation/structuration des descriptions et s'il faut ajouter des éléments. 
Merci pour ta contribution ! :)

Je te propose d'ajouter la description de ton corpus dans https://github.com/HTR-United/htr-united/blob/master/htr-united.yml
