### ISSUE TITLE
Revoir la quantification des mains

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#19]
Dans certains cas il est impossible de quantifier de manière exacte le nombre de mains (ex : docs dont les scripteurs sont anonymes), auquel cas une estimation chiffrée du nombre de mains n'a pas de sens. 

Je propose d'opter pour un système avec un choix entre une quantification exacte ou une approximation par range.

**Comment by PonteIneptique** [comment]
Fixed ?

**Comment by alix-tz** [comment]
Tout à fait !
