### ISSUE TITLE
Mini-app javascript pour générer les éléments YAML

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united#4]
Todo:

- [x] Application JS pour générer le YAML
- [ ] **JOLIE**
- [ ] Complète ?

**Comment by alix-tz** [comment]
Perspective d'amélioration vraiment pas prioritaires : 
- limiter le champs "hands" pour qu'il n'aille pas en dessous de 1
- ajouter d'autres options de license
- encadrer l'expression des dates, surtout si elles sont approximatives

**Comment by PonteIneptique** [comment]
Pour info @alix-tz , j'ai utilisé un champ `number` sur les dates et hands.
Après, si les gens mettent `-1` ou autre, on corrigera en PR non ? Il me semble plus logique de se concentrer sur les autres licences, les autres formats, etc. et la routine d'export du YAML potentiellement ?
Ah, et sur un minimum de mise en page de ces fichiers HTML :)

**Comment by PonteIneptique** [comment]
Quelles sont les licences à ajouter ? Tu as une idée ?

**Comment by PonteIneptique** [comment]
La page a un bug: elle affiche data.metric à la place de page/line pour les mesures.

**Comment by PonteIneptique** [comment]
Allez, done :)
