### ISSUE TITLE
Discussion sur la license

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#48]
@PonteIneptique j'ouvre un espace de discussion pour correctement choisir la license applicable au catalogue. 

- sur `htr-united.yml` et le contenu de `catalog/` Il me semble que cette licence devrait être CC0, puisqu'il n'est pas question de s'approprier des droits de citation sur des métadonnées générées par d'autres ; et il me semblerait logique de proposer aux déposants qu'ils renoncent à des droits sur les métadonnées transmises.

- pour le reste du répo, comment verrais-tu les choses ?

**Comment by PonteIneptique** [comment]
Cc0, ça me semble difficile de revendiquer des droits sur des nombres de
lignes...
Sur le reste, mozilla license?

Le lun. 31 janv. 2022 à 7:06 PM, Alix Chagué ***@***.***> a
écrit :

**Comment by alix-tz** [comment]
Le reste -> le site internet, HUMG et HTRUX ?

**Comment by alix-tz** [comment]
Va pour CC0 sur tout le repo htr-united en tout ça 👍
