### ISSUE TITLE
Passez le repo en repo avec page github.io ?

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united#5]
Est-ce que cela serait pas utile pour l'application JS notamment ?

**Comment by alix-tz** [comment]
Je veux bien m'en charger

**Comment by alix-tz** [comment]
J'ai préféré créer un autre répo dédié à la page github éviter de renommer le répo courant : https://github.com/HTR-United/htr-united.github.io

**Comment by alix-tz** [comment]
-> https://htr-united.github.io/
