### ISSUE TITLE
Il faudrait clarifier la distinction entre "file" et "image"

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#53]
Je pense que les deux sont confondus, donc rajouter une doc.

Peut-être aussi rajouter dans le formulaire que pour obtenir ces chiffres, il est possible d'utiliser HUMGenerator.

Et pour permettre d'avoir des métriques d'ensemble et constantes sur l'ensemble des dépôts, voir à imposer un des champes (par exemple "page") ?

**Comment by PonteIneptique** [comment]
> Peut-être aussi rajouter dans le formulaire que pour obtenir ces chiffres, il est possible d'utiliser HUMGenerator.
Il serait cool d'ailleurs de rendre disponible HUMGenerator en mode app (en uploadant que les fichiers XML), mais c'est une autre histoire.

Un fichier peut facilement comprendre deux pages dans les manuscrits numérisés, c'est la principale différence

**Comment by alix-tz** [comment]
Je pense que je me suis trompé de mot, parce qu'en effet, on peut avoir 1 fichier = 2 page. Je pense que je voulais dire clarifier ce qui constitue un fichier.

Par exemple, dans un repo avec 3 images, 3 fichiers XML -> on doit indiquer 6 files, ou bien 3? 

Si file se réfère seulement aux fichiers XML, quelle serait l'intérêt de renseigner le volume d'image et le volume de fichiers XML ?

**Comment by PonteIneptique** [comment]
Effectivement: file= XML File :)
