### ISSUE TITLE
add distinction language / script / mode

### ISSUE THREAD

**Issue by dstoekl** [HTR-United/htr-united#62]
you can have Latin script and English or Gaelic language.
you can have Arabic or Persian or Yiddish in Hebrew script etc.
AND you want to distinguish between print, manuscript, inscription etc.
so 3 and not 2 levels.

**Comment by PonteIneptique** [comment]
Dear @dstoekl ,
We already have the distinction language / script / mode, except for mode = inscriptions, but we have yet to stumble on a dataset that is inscriptions (but this is something to keep in mind for later). Is there something in particular that made you think there is no distinction ?

**Comment by dstoekl** [comment]
This is not correct. You cannot distinguish between datasets in Arabic language in Hebrew script and Arabic language in Arabic script.

**Comment by PonteIneptique** [comment]
![image](https://user-images.githubusercontent.com/1929830/156208399-557f4ef1-c441-4bed-89b6-b44f9e4988d0.png)

Isn't this what you mean ?

**Comment by dstoekl** [comment]
Frontoffice backoffice difference? This is what I see in the search engine: 
![image](https://user-images.githubusercontent.com/39535215/156209783-3d6f2a21-76d5-49d4-aedf-61f2a4db02ab.png)

**Comment by PonteIneptique** [comment]
Seems more like a browser issue. What do you use as a browser ?

**Comment by PonteIneptique** [comment]
Oh ! It's not a schema issue, nor a form issue, you are talking about the browsing interface. We did not implement the filter for script. even if the data are there.
We'll add it

**Comment by PonteIneptique** [comment]
Concerns the website, closing this as this is the repository for the catalog. Follow up in [#80](https://github.com/HTR-United/htr-united.github.io/issues/80)
