### ISSUE TITLE
(contact) Modèle de segmentation et de reconnaissance optique de caractères - Kraken - Incunables sévillans 1494-1500

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united#68]
Contacter Matthias Gille Levenson pour proposer de reférencer la vérité de terrain de : 

- https://zenodo.org/record/5562596#.Ynzu9FTP3mE

**Comment by PonteIneptique** [comment]
Fait :D

**Comment by alix-tz** [comment]
> @alix-tz, es-tu l'autrice du tuto eScriptorium de Lectaurep ?

Tout à fait !

**Comment by matgille** [comment]
Serais-tu intéressée / aurais-tu le temps de le transformer en leçon pour Programming Historian ?

**Comment by PonteIneptique** [comment]
![image](https://user-images.githubusercontent.com/1929830/168090069-ce3290f9-1a6d-491d-a0ae-c3ff74313606.png)

**Comment by alix-tz** [comment]
@matgille je ne vois pas le dataset dans le catalogue, est-ce que tu avais transmis une description ? (si oui, je chercherai mieux)

**Comment by matgille** [comment]
Bonjour @alix-tz, je vais voir ça

**Comment by PonteIneptique** [comment]
Fixed :)
