### ISSUE TITLE
Contact INHA for their Transkribus data

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united#73]
Check with https://skylab.inha.fr/PENSE/LettresDeJacquesDoucetAReneJean1908-1929/ where it's written Transkribus is used.

@alix-tz @emchateau You might know someone inside ?

**Comment by emchateau** [comment]
Antoine Courtin was in charge of this project, but he is now in Orsay. I can write him to know who is actually in charge.
Best regards,

**Comment by alix-tz** [comment]
I was in touch with Jean-Christophe Carius (@jccarius) last year, he was ok with the idea of indexing their data in HTR-United, but we probably need to recall them :)

**Comment by jccarius** [comment]
Thanks for the reminder. We plan to share the documents very soon. (in July or August)

**Comment by jccarius** [comment]
The repository for the transcriptions of "Les Papiers Barye" project is open. We hope to be able to share the "Correspondance Jacques Doucet / René jean" data (capta) quite soon...

===== YAML =====
schema: https://htr-united.github.io/schema/2022-04-15/schema.json
title: Les Papiers Barye
url: https://gitlab.inha.fr/snr/LesPapiersBarye
authors:
  - name: Claass
    surname: Victor
    roles:
      - transcriber
      - project-manager
      - quality-control
  - name: Gain
    surname: Justine
    roles:
      - transcriber
      - quality-control
  - name: Martin-Vigier
    surname: Suzanne
    roles:
      - transcriber
      - quality-control
institutions:
  - name: Institut National de l'histoire de l'art (INHA)
    roles:
      - transcriber
      - aligner
      - project-manager
      - quality-control
      - digitization
description: >-
  Ensemble de documents autour du sculpteur Antoine-Louis Barye. Paris,
  Bibliothèque de l’Institut national d’histoire de l’art, collections Jacques
  Doucet, Archives 166. Institut National de l’Histoire de l’art (INHA) /
  Set of documents about the sculptor Antoine-Louis Barye. Paris,
  Library of the Institut national d'histoire de l'art, Jacques
  Doucet, Archives 166. National Institute of Art History (INHA)
project-website: https://skylab.inha.fr/PENSE/LesPapiersBarye/
language:
  - fra
production-software: Transkribus
script:
  - iso: Latn
script-type: mainly-manuscript
time:
  notBefore: '1819'
  notAfter: '1914'
hands:
  count: more-than-10
  precision: exact
license:
  - name: Etalab OL 2.0
    url: https://spdx.org/licenses/etalab-2.0.html
format: Alto-XML
volume:
  - metric: characters
    count: 362629
  - metric: lines
    count: 17880
  - metric: pages
    count: 918
  - metric: files
    count: 918

**Comment by PonteIneptique** [comment]
Very very good news ! Thank you !

**Comment by alix-tz** [comment]
Cool ! :D 

Just a question regarding the images: are they accessible anywhere?

**Comment by jccarius** [comment]
The images are on the IIIF server of The INHA digital library.
Each XML-ALTO files indicates its corresponding IIIF urls in the
"Description / fileIdentifier" tag.
Example:
<alto>
  <Description>
    <sourceImageInformation>
      <fileIdentifier>
https://bibliotheque-numerique.inha.fr/i/?IIIF=/65/47/f8/b8/6547f8b8-4a80-4349-ae34-9ccb5023a304/iiif/1101_doucet_ARCHIVES166_2_2_001-002_000001.tif/full/2082,/0/default.jpg
</fileIdentifier>
    </sourceImageInformation>
  ...
</Description>
...
</alto>

Le ven. 9 sept. 2022 à 16:08, Alix Chagué ***@***.***> a
écrit :

**Comment by jccarius** [comment]
The repository for the transcriptions of "La Correspondance Jaques Doucet - René Jean" is open.
The corresponding image files are on Gallica as indicated in the Description/sourceImageInformation/fileIdentifier element of each ALTO document.
===== YAML =====
schema: https://htr-united.github.io/schema/2022-04-15/schema.json
title: La Correspondances Jacques Doucet - René Jean
url: https://gitlab.inha.fr/snr/LaCorrespondanceDoucetReneJean
authors:
  - name: Cugy
    surname: Pascale
    roles:
      - transcriber
      - project-manager
      - quality-control
  - name: Fieschi
    surname: Caroline
    roles:
      - project-manager
      - quality-control
  - name: Peyrard
    surname: Alix
    roles:
      - transcriber
      - quality-control
  - name: Prohin
    surname: Lucie
    roles:
      - transcriber
      - quality-control
  - name: Sarda
    surname: Marie-Anne
    roles:
      - support
institutions:
  - name: Institut National de l'histoire de l'art (INHA)
    roles:
      - transcriber
      - project-manager
      - quality-control
  - name: Bibliothèque nationale de France
    roles:
    - digitization
description: >-
  Projet entrepris dans le cadre du programme La Bibliothèque d’art et
  d’archéologie de Jacques Doucet : corpus, savoirs et réseaux de l’Institut
  national d’histoire de l’art à partir d’un corpus de lettres et documents
  conservés au Département des manuscrits de la Bibliothèque nationale de France
  sous la cote NAF 13124, une des principales sources sur la relation entre
  Doucet et René Jean qu’il engagea comme bibliothécaire le 2 juin 1908.
project-website: https://skylab.inha.fr/PENSE/LettresDeJacquesDoucetAReneJean1908-1929/
language:
  - fra
production-software: Transkribus
script:
  - iso: Latn
script-type: mainly-manuscript
time:
  notBefore: '1908'
  notAfter: '1929'
hands:
  count: less-than-11
  precision: exact
license:
  - name: Etalab OL 2.0
    url: https://spdx.org/licenses/etalab-2.0.html
format: Alto-XML
volume:
  - metric: characters
    count: 83312
  - metric: lines
    count: 2987
  - metric: pages
    count: 200
  - metric: files
    count: 200

**Comment by PonteIneptique** [comment]
Merci, pull request ouverte pour @alix-tz
