### ISSUE TITLE
HTR-United plus large ?

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united#8]
Vraie réflexion mais serait-il imaginable de faire des dépôts par période de langue ?

HTR-United-FRO
HTR-United-FRA
HTR-United-FRE

Ou garde-t-on HTR United spécifique sur les dates, ce qui me semble bien aussi.

**Comment by alix-tz** [comment]
Je suis d'avis d'élargir HTR-United au maximum (n'importe quelle donnée permettant l'entraînement de modèles de transcription) quitte à spécifier des ensembles cohérent au fur et à mesure que des groupes de données apparaissent. Qu'en penses-tu ?

**Comment by PonteIneptique** [comment]
Vu les discussions, on a effectivement élargi ;)
