### ISSUE TITLE
YML generation: name and surname is switched in form hints

### ISSUE THREAD

**Issue by hajicj** [HTR-United/htr-united#95]
When adding project members in the YML generation form, the hints for Last name and First name don't correspond to the generated YML. The first field with hint Last name is stored as `name` and vice versa the second field with hint First name is stored as `surname`.

**Comment by PonteIneptique** [comment]
Oh.... The issue might be more complicated than a quick fix, as I wonder if I did not mistake one for the other everywhere... Thanks for the catch !

**Comment by alix-tz** [comment]
Closing this issue because it's fixed! Thank you again for signaling the problem!
